apiVersion: v1
kind: Service
metadata:
  name: microservice-client-nextjs
spec:
  selector:
    component: microservice-client-nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
