apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-client-nextjs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/nk7771611/k8s.git
    targetRevision: HEAD
    path: microservice-client-nextjs
  destination:
    server: https://kubernetes.default.svc
    namespace: defalut
